reporter: "xcode"

disabled_rules:
 - control_statement
 - trailing_whitespace
 - file_length
 - unused_optional_binding
 - notification_center_detachment
 - force_cast

opt_in_rules:
 - empty_count
 - class_delegate_protocol
 - closure_end_indentation
 - closure_spacing
 - contains_over_first_not_nil
 - empty_xctest_method
 - explicit_init
 - fatal_error_message
 - first_where


function_parameter_count:
 warning: 10
 error: 15


large_tuple:
 warning: 3
 error: 5


line_length:
 warning: 136
 error: 200


vertical_whitespace:
 max_empty_lines: 2


excluded:
 - Pods 
 - WalletTests
